spring.application.name=Learn-Jenkins-Docker
server.port=8092
app.cors.allowed-origins=http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,http://127.0.0.1:3001,http://localhost:3500,http://127.0.0.1:3500
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://sjroot9:gvBZZkzcKXWGGRru@recharge.xniae.mongodb.net/hotel_db?retryWrites=true&w=majority}
